theme: jekyll-theme-minimal
title: Home page of an Academic Vagabond
description: My original home page was made at the Centre for Experimental and Constructive Mathematics (www.cecm.sfu.ca) in 1995; 
my home institution was the University of Western Ontario and I moved all that material to UWO in 1996.  The web page was updated 
periodically over the decades that followed, finally being pushed to htpps:/publish.uwo.ca/~rcorless, on a server that is destined 
for obsolescent oblivion.  Several helpful people have suggested that the Vagabond move to GitHub, so here I am.
