theme: jekyll-theme-minimal
title: Rob Corless, Academic Vagabond
description: Container for links to papers and other expositions; connective tissue for an internet world
![Image](https://github.com/rcorless/rcorless.github.io/blob/main/Geometric_5x5_gallery%402x.jpg)
